import React from 'react';
import { FileText, Printer } from 'lucide-react';
import type { RequestTemplateDraft, RequestTemplateDraftAction } from '../../../lib/requestTemplateEditorModel';

interface Props { draft: RequestTemplateDraft; dispatch: (action: RequestTemplateDraftAction) => void; }

const RequestTemplatePrintSection: React.FC<Props> = ({ draft, dispatch }) => <section className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900"><header className="border-b border-slate-200 px-5 py-4 dark:border-slate-700"><h2 className="flex items-center gap-2 text-lg font-bold text-slate-800 dark:text-white"><Printer size={19} className="text-accent" /> In đề xuất</h2><p className="mt-1 text-sm text-slate-500">Thiết lập cách người dùng xuất bản in cho đề xuất đã gửi.</p></header><div className="space-y-4 p-5"><label className="flex cursor-pointer items-center justify-between rounded-xl border border-slate-200 p-4 dark:border-slate-700"><span><span className="block text-sm font-bold text-slate-700 dark:text-slate-200">Cho phép in từ trình duyệt / PDF</span><span className="mt-1 block text-xs text-slate-400">Bật mặc định, dùng bố cục in chuẩn của Vioo.</span></span><input type="checkbox" checked={draft.print.browserPrintEnabled} onChange={event => dispatch({ type: 'SET_PRINT', print: { ...draft.print, browserPrintEnabled: event.target.checked } })} className="h-5 w-5 accent-emerald-600" /></label><div className="rounded-xl border border-dashed border-slate-300 p-4 text-sm dark:border-slate-700"><div className="flex items-center gap-2 font-bold text-slate-700 dark:text-slate-200"><FileText size={18} /> Mẫu DOCX theo phiên bản</div><p className="mt-2 text-slate-500">Upload DOCX được bật sau khi backend cấp mã phiên bản nháp và xác thực placeholder. Điều này bảo đảm file luôn được lưu riêng theo version bất biến, không ghi trực tiếp một đường dẫn không được policy Storage cho phép.</p><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500"><code>${'{code}'}</code><code>${'{title}'}</code><code>${'{creator_name}'}</code><code>${'{created_at_full}'}</code><code>${'{field_amount}'}</code><code>${'{approval_summary}'}</code></div></div></div></section>;

export default RequestTemplatePrintSection;
