begin read only;
set local statement_timeout='25s';
select jsonb_build_object(
'columns',(select jsonb_agg(jsonb_build_object('table',table_name,'column',column_name,'type',data_type)) from information_schema.columns where table_schema='public' and table_name in ('purchase_orders','purchase_order_delivery_batches','purchase_order_delivery_lines','purchase_order_request_lines','inventory_balances','inventory_ledger_entries','supplier_invoices','supplier_invoice_payable_links','supplier_payment_batches','project_work_boq_items','material_budget_items')),
'constraints',(select jsonb_agg(jsonb_build_object('table',conrelid::regclass::text,'name',conname,'type',contype,'definition',pg_get_constraintdef(oid))) from pg_constraint where connamespace='public'::regnamespace and conrelid::regclass::text in ('purchase_orders','purchase_order_delivery_batches','purchase_order_delivery_lines','purchase_order_request_lines','inventory_balances','supplier_invoices','supplier_invoice_payable_links','supplier_payment_allocations','project_document_links','material_request_fulfillment_lines')),
'views',(select jsonb_agg(jsonb_build_object('name',relname,'options',reloptions)) from pg_class where relnamespace='public'::regnamespace and relkind='v' and relname ~ '(supplier|inventory|project|material|purchase)'),
'policies',(select jsonb_agg(jsonb_build_object('table',tablename,'name',policyname,'cmd',cmd,'roles',roles,'qual',qual,'check',with_check)) from pg_policies where schemaname='public' and tablename in ('purchase_orders','purchase_order_delivery_batches','purchase_order_delivery_lines','purchase_order_request_lines','supplier_invoices','supplier_payment_batches','supplier_payment_allocations','inventory_ledger_entries','inventory_balances')),
'functions',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'security_definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl,'definition',pg_get_functiondef(p.oid))) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','app_private') and p.proname in ('post_inventory_ledger_entry','sync_wms_transaction_to_inventory_ledger','approve_material_po_quality','finalize_material_po_receipt','post_supplier_payment_batch','record_supplier_invoice_reconciliation_v2','sync_supplier_payable_from_purchase_order','sync_fulfillment_receipt_for_transaction','assert_purchase_order_room_write_allowed','guard_purchase_order_request_line_write'))
) as audit;
rollback;
