// Từ điển nghiệp vụ cho tìm kiếm: viết tắt, đồng nghĩa và từ chỉ loại hồ sơ. Tất cả ở dạng
// đã bỏ dấu (foldVi). Mỗi nhóm là các cách nói cùng một thứ — gõ cách nào cũng ra.

import type { SearchKind } from './searchTypes';

export const SYNONYM_GROUPS: readonly (readonly string[])[] = [
  ['po', 'don hang', 'don mua', 'don mua hang', 'dat hang', 'purchase order', 'order'],
  ['ncc', 'nha cung cap', 'supplier', 'vendor'],
  ['hd', 'hop dong', 'contract'],
  ['hdld', 'hop dong lao dong'],
  ['nv', 'nhan vien', 'nhan su', 'employee', 'staff', 'nguoi lao dong'],
  ['da', 'du an', 'cong trinh', 'cong truong', 'project'],
  ['vt', 'vat tu', 'vat lieu', 'material', 'hang hoa'],
  ['tt', 'thanh toan', 'payment'],
  ['dntt', 'de nghi thanh toan'],
  ['dnc', 'de nghi chi', 'chi tien'],
  ['dntu', 'de nghi tam ung', 'tam ung', 'advance'],
  ['yc', 'yeu cau', 'de xuat', 'request'],
  ['pyc', 'phieu yeu cau'],
  ['dxvt', 'de xuat vat tu', 'yeu cau vat tu'],
  ['pnk', 'phieu nhap kho', 'nhap kho', 'nhap hang'],
  ['pxk', 'phieu xuat kho', 'xuat kho', 'cap phat'],
  ['pck', 'chuyen kho', 'dieu chuyen'],
  ['cc', 'cham cong', 'check in', 'checkin', 'diem danh', 'vao ca'],
  ['np', 'nghi phep', 'xin nghi', 'don nghi', 'leave'],
  ['ts', 'tai san', 'asset', 'thiet bi'],
  ['ccdc', 'cong cu dung cu'],
  ['cdt', 'chu dau tu', 'khach hang', 'customer'],
  ['tp', 'thau phu', 'nha thau phu', 'nha thau', 'subcontractor'],
  ['bc', 'bao cao', 'report', 'thong ke'],
  ['nk', 'nhat ky', 'nhat ky cong truong', 'daily log'],
  ['qt', 'quy trinh', 'workflow'],
  ['vb', 'van ban', 'cong van', 'office'],
  ['kk', 'kiem ke', 'stock count'],
  ['bl', 'bang luong', 'luong', 'payroll', 'phieu luong'],
  ['dat xe', 'xe', 'vehicle', 'booking', 'xe cong ty'],
  ['ton', 'ton kho', 'stock', 'inventory'],
  ['cv', 'cong viec', 'task', 'viec'],
  ['tc', 'tai chinh', 'finance', 'ke toan'],
  ['ns', 'ngan sach', 'budget'],
  ['phai thu', 'cong no phai thu', 'receivable', 'thu tien'],
  ['phai tra', 'cong no', 'payable', 'no ncc'],
  ['hoa don', 'invoice', 'hddt'],
  ['bg', 'bao gia', 'quotation'],
  ['tb', 'thong bao', 'notification'],
  ['gop y', 'feedback', 'bao loi', 'bug'],
  ['ai', 'tro ly', 'chatbot', 'hoi dap'],
  ['cai dat', 'settings', 'cau hinh', 'thiet lap'],
  ['pq', 'phan quyen', 'quyen', 'permission'],
  ['tien do', 'gantt', 'schedule'],
  ['dashboard', 'tong quan', 'overview'],
  ['mua nong', 'hot purchase', 'mua gap'],
  ['dieu dong', 'dieu chuyen nhan su', 'phan cong cong truong'],
  ['bang cong', 'timesheet', 'tong hop cong'],
  ['sdt', 'so dien thoai', 'dien thoai', 'phone'],
  ['mst', 'ma so thue', 'tax code'],
  ['quy', 'thu chi', 'quy tien mat', 'so quy'],
];

/** Từ chỉ loại hồ sơ: gõ kèm thì ưu tiên loại đó ("po thép" → đơn hàng có thép). */
export const KIND_WORDS: Readonly<Record<string, readonly SearchKind[]>> = {
  po: ['purchase_order'], 'don hang': ['purchase_order'], 'don mua': ['purchase_order'], 'dat hang': ['purchase_order'], 'mua hang': ['purchase_order'],
  da: ['project'], 'du an': ['project'], 'cong trinh': ['project'], 'cong truong': ['project'],
  nv: ['employee'], 'nhan vien': ['employee'], 'nhan su': ['employee'], sdt: ['employee'],
  vt: ['item'], 'vat tu': ['item', 'material_request'], 'vat lieu': ['item'], 'ton kho': ['item'], 'ma vat tu': ['item', 'material_code'],
  'phieu kho': ['wms_tx'], 'nhap kho': ['wms_tx'], 'xuat kho': ['wms_tx'], 'chuyen kho': ['wms_tx'], pnk: ['wms_tx'], pxk: ['wms_tx'],
  dxvt: ['material_request'], 'de xuat vat tu': ['material_request'], 'yeu cau vat tu': ['material_request'],
  rq: ['rq'], yc: ['rq'], 'yeu cau': ['rq', 'material_request'], 'de xuat': ['rq', 'material_request'], pyc: ['rq'],
  qt: ['wf'], 'quy trinh': ['wf'],
  ncc: ['partner', 'supplier_contract'], 'nha cung cap': ['partner', 'supplier_contract'], 'doi tac': ['partner'], mst: ['partner'],
  cdt: ['partner', 'customer_contract'], 'chu dau tu': ['partner', 'customer_contract'], 'khach hang': ['partner', 'customer_contract'],
  hd: ['customer_contract', 'subcontract', 'supplier_contract'], 'hop dong': ['customer_contract', 'subcontract', 'supplier_contract'],
  tp: ['subcontract'], 'thau phu': ['subcontract'],
  ts: ['asset'], 'tai san': ['asset'], 'thiet bi': ['asset'],
  vb: ['office_doc'], 'van ban': ['office_doc'], 'cong van': ['office_doc'],
  cv: ['work_task'], 'cong viec': ['work_task'], task: ['work_task'],
  dntt: ['payment_request'], dnc: ['payment_request'], 'de nghi chi': ['payment_request'], 'de nghi thanh toan': ['payment_request'], 'tam ung': ['payment_request'],
  xe: ['vehicle_booking'], 'dat xe': ['vehicle_booking'],
  np: ['leave'], 'nghi phep': ['leave'], 'don nghi': ['leave'],
  'gop y': ['feedback'], 'bao loi': ['feedback'],
  'cap ma': ['material_code'],
};

/** Từ hay gặp trong dữ liệu xây dựng (có dấu để gợi ý "Có phải bạn muốn tìm…"). Dùng sửa lỗi gõ. */
export const DOMAIN_WORDS: readonly string[] = [
  'thép', 'xi', 'măng', 'cát', 'đá', 'gạch', 'bê', 'tông', 'cốt', 'dầm', 'sàn', 'móng', 'cọc', 'tôn', 'ống', 'nước', 'điện',
  'dây', 'cáp', 'sơn', 'kính', 'nhôm', 'gỗ', 'ván', 'khuôn', 'giàn', 'giáo', 'cẩu', 'thang', 'máy', 'trộn', 'bơm', 'hàn',
  'que', 'bulông', 'ốc', 'vít', 'đinh', 'lưới', 'tấm', 'trần', 'thạch', 'cao', 'chống', 'thấm', 'phụ', 'gia', 'hóa', 'chất',
  'nhà', 'xưởng', 'kho', 'bãi', 'vật', 'tư', 'liệu', 'công', 'trình', 'trường', 'dự', 'án', 'hợp', 'đồng', 'thầu', 'chủ',
  'đầu', 'khách', 'hàng', 'cung', 'ứng', 'mua', 'bán', 'nhập', 'xuất', 'chuyển', 'phiếu', 'yêu', 'cầu', 'đề', 'nghị', 'thanh',
  'toán', 'tạm', 'quyết', 'nghiệm', 'thu', 'chi', 'quỹ', 'ngân', 'sách', 'lương', 'chấm', 'phép', 'nhân', 'viên', 'sự', 'tài',
  'sản', 'thiết', 'bị', 'báo', 'nhật', 'ký', 'tiến', 'độ', 'kế', 'hoạch', 'quy', 'văn', 'bản', 'việc', 'xe', 'góp', 'đơn',
  'mã', 'số', 'thuế', 'địa', 'chỉ', 'thoại', 'giám', 'đốc', 'phòng', 'kỹ', 'bảo', 'vệ', 'an', 'toàn', 'chất', 'lượng',
  'hoàn', 'thành', 'duyệt', 'chờ', 'từ', 'chối', 'hủy', 'tồn', 'kiểm', 'kê', 'lao', 'động', 'nghỉ', 'đặt', 'gửi', 'điều',
];
