-- Managed-schema application policies and triggers.
set search_path = public, app_private, private, extensions, auth, storage, pg_catalog;
revoke all privileges on table auth.users from anon, authenticated, service_role;
revoke all privileges on table storage.objects from anon, authenticated, service_role;
grant DELETE, UPDATE on table storage.objects to anon;
grant DELETE, INSERT, SELECT, UPDATE on table storage.objects to authenticated;
drop policy if exists "Allow delete from project-attachments" on storage.objects;
create policy "Allow delete from project-attachments" on storage.objects as PERMISSIVE for DELETE to public using (((bucket_id = 'project-attachments'::text) AND (split_part(name, '/'::text, 1) <> 'quality'::text)));
drop policy if exists "Allow public read from avatars" on storage.objects;
create policy "Allow public read from avatars" on storage.objects as PERMISSIVE for SELECT to public using ((bucket_id = 'avatars'::text));
drop policy if exists "Allow public upload to avatars" on storage.objects;
create policy "Allow public upload to avatars" on storage.objects as PERMISSIVE for INSERT to public with check ((bucket_id = 'avatars'::text));
drop policy if exists "Allow update in project-attachments" on storage.objects;
create policy "Allow update in project-attachments" on storage.objects as PERMISSIVE for UPDATE to public using (((bucket_id = 'project-attachments'::text) AND (split_part(name, '/'::text, 1) <> 'quality'::text))) with check (((bucket_id = 'project-attachments'::text) AND (split_part(name, '/'::text, 1) <> 'quality'::text)));
drop policy if exists "Allow upload to project-attachments" on storage.objects;
create policy "Allow upload to project-attachments" on storage.objects as PERMISSIVE for INSERT to public with check (((bucket_id = 'project-attachments'::text) AND (split_part(name, '/'::text, 1) <> 'quality'::text)));
drop policy if exists "Public Access project-photos" on storage.objects;
create policy "Public Access project-photos" on storage.objects as PERMISSIVE for ALL to public using ((bucket_id = 'project-photos'::text)) with check ((bucket_id = 'project-photos'::text));
drop policy if exists "Public read access for project-attachments" on storage.objects;
create policy "Public read access for project-attachments" on storage.objects as PERMISSIVE for SELECT to public using ((bucket_id = 'project-attachments'::text));
drop policy if exists auth_delete on storage.objects;
create policy auth_delete on storage.objects as PERMISSIVE for DELETE to public using ((bucket_id = 'project-files'::text));
drop policy if exists auth_insert on storage.objects;
create policy auth_insert on storage.objects as PERMISSIVE for INSERT to public with check ((bucket_id = 'project-files'::text));
drop policy if exists chat_v2_attachments_storage_delete on storage.objects;
create policy chat_v2_attachments_storage_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'chat-attachments'::text) AND (is_admin() OR (owner_id = ( SELECT (auth.uid())::text AS uid)) OR app_private.chat_v2_can_manage(app_private.chat_v2_storage_conversation_id(name), current_app_user_id()))));
drop policy if exists chat_v2_attachments_storage_insert on storage.objects;
create policy chat_v2_attachments_storage_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'chat-attachments'::text) AND app_private.chat_v2_is_participant(app_private.chat_v2_storage_conversation_id(name), current_app_user_id())));
drop policy if exists chat_v2_attachments_storage_select on storage.objects;
create policy chat_v2_attachments_storage_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'chat-attachments'::text) AND (is_admin() OR app_private.chat_v2_is_participant(app_private.chat_v2_storage_conversation_id(name), current_app_user_id()))));
drop policy if exists chat_v2_attachments_storage_update on storage.objects;
create policy chat_v2_attachments_storage_update on storage.objects as PERMISSIVE for UPDATE to authenticated using (((bucket_id = 'chat-attachments'::text) AND app_private.chat_v2_is_participant(app_private.chat_v2_storage_conversation_id(name), current_app_user_id()))) with check (((bucket_id = 'chat-attachments'::text) AND app_private.chat_v2_is_participant(app_private.chat_v2_storage_conversation_id(name), current_app_user_id())));
drop policy if exists chat_v2_storage_app_access on storage.objects;
create policy chat_v2_storage_app_access on storage.objects as RESTRICTIVE for ALL to authenticated using (((bucket_id <> 'chat-attachments'::text) OR app_private.chat_v2_has_app_access(current_app_user_id()))) with check (((bucket_id <> 'chat-attachments'::text) OR app_private.chat_v2_has_app_access(current_app_user_id())));
drop policy if exists checkin_photos_delete on storage.objects;
create policy checkin_photos_delete on storage.objects as PERMISSIVE for DELETE to authenticated using ((bucket_id = 'checkin-photos'::text));
drop policy if exists checkin_photos_insert on storage.objects;
create policy checkin_photos_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check ((bucket_id = 'checkin-photos'::text));
drop policy if exists checkin_photos_select on storage.objects;
create policy checkin_photos_select on storage.objects as PERMISSIVE for SELECT to public using ((bucket_id = 'checkin-photos'::text));
drop policy if exists checkin_photos_update on storage.objects;
create policy checkin_photos_update on storage.objects as PERMISSIVE for UPDATE to authenticated using ((bucket_id = 'checkin-photos'::text)) with check ((bucket_id = 'checkin-photos'::text));
drop policy if exists contract_files_delete on storage.objects;
create policy contract_files_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'contract-files'::text) AND is_module_admin('HD'::text)));
drop policy if exists contract_files_insert on storage.objects;
create policy contract_files_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'contract-files'::text) AND is_module_admin('HD'::text)));
drop policy if exists contract_files_select on storage.objects;
create policy contract_files_select on storage.objects as PERMISSIVE for SELECT to authenticated using ((bucket_id = 'contract-files'::text));
drop policy if exists contract_files_update on storage.objects;
create policy contract_files_update on storage.objects as PERMISSIVE for UPDATE to authenticated using (((bucket_id = 'contract-files'::text) AND is_module_admin('HD'::text))) with check (((bucket_id = 'contract-files'::text) AND is_module_admin('HD'::text)));
drop policy if exists custom_material_storage_delete on storage.objects;
create policy custom_material_storage_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'custom-material-attachments'::text) AND app_private.custom_material_storage_can_mutate(name)));
drop policy if exists custom_material_storage_insert on storage.objects;
create policy custom_material_storage_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'custom-material-attachments'::text) AND app_private.custom_material_storage_can_mutate(name)));
drop policy if exists custom_material_storage_select on storage.objects;
create policy custom_material_storage_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'custom-material-attachments'::text) AND app_private.custom_material_storage_can_select(name)));
drop policy if exists custom_material_storage_update on storage.objects;
create policy custom_material_storage_update on storage.objects as PERMISSIVE for UPDATE to authenticated using (((bucket_id = 'custom-material-attachments'::text) AND app_private.custom_material_storage_can_mutate(name))) with check (((bucket_id = 'custom-material-attachments'::text) AND app_private.custom_material_storage_can_mutate(name)));
drop policy if exists feedback_attachments_storage_delete on storage.objects;
create policy feedback_attachments_storage_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'feedback-attachments'::text) AND (split_part(name, '/'::text, 1) = 'feedback'::text) AND (split_part(name, '/'::text, 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text) AND ((EXISTS ( SELECT 1
   FROM feedback_attachments fa
  WHERE ((fa.storage_bucket = 'feedback-attachments'::text) AND (fa.storage_path = objects.name) AND ((fa.uploaded_by = current_app_user_id()) OR app_private.feedback_can_manage())))) OR (owner_id = ( SELECT (auth.uid())::text AS uid)))));
drop policy if exists feedback_attachments_storage_insert on storage.objects;
create policy feedback_attachments_storage_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'feedback-attachments'::text) AND (split_part(name, '/'::text, 1) = 'feedback'::text) AND (split_part(name, '/'::text, 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text) AND app_private.feedback_item_can_select((split_part(name, '/'::text, 2))::uuid)));
drop policy if exists feedback_attachments_storage_select on storage.objects;
create policy feedback_attachments_storage_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'feedback-attachments'::text) AND (split_part(name, '/'::text, 1) = 'feedback'::text) AND (split_part(name, '/'::text, 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text) AND app_private.feedback_item_can_select((split_part(name, '/'::text, 2))::uuid)));
drop policy if exists hr_documents_template_delete on storage.objects;
create policy hr_documents_template_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'hr-documents'::text) AND app_private.current_user_has_hrm_template_permission('hrm.document.manage'::text)));
drop policy if exists hr_documents_template_insert on storage.objects;
create policy hr_documents_template_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'hr-documents'::text) AND app_private.current_user_has_hrm_template_permission('hrm.document.manage'::text)));
drop policy if exists hr_documents_template_select on storage.objects;
create policy hr_documents_template_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'hr-documents'::text) AND app_private.current_user_has_hrm_template_permission('hrm.document.view'::text)));
drop policy if exists hr_documents_template_update on storage.objects;
create policy hr_documents_template_update on storage.objects as PERMISSIVE for UPDATE to authenticated using (((bucket_id = 'hr-documents'::text) AND app_private.current_user_has_hrm_template_permission('hrm.document.manage'::text))) with check (((bucket_id = 'hr-documents'::text) AND app_private.current_user_has_hrm_template_permission('hrm.document.manage'::text)));
drop policy if exists hrm_private_import_delete on storage.objects;
create policy hrm_private_import_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'hrm-private-imports'::text) AND (split_part(name, '/'::text, 1) = (current_app_user_id())::text) AND app_private.current_user_has_hrm_template_permission('hrm.employee.import'::text)));
drop policy if exists hrm_private_import_insert on storage.objects;
create policy hrm_private_import_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'hrm-private-imports'::text) AND (split_part(name, '/'::text, 1) = (current_app_user_id())::text) AND app_private.current_user_has_hrm_template_permission('hrm.employee.import'::text)));
drop policy if exists hrm_private_import_select on storage.objects;
create policy hrm_private_import_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'hrm-private-imports'::text) AND (split_part(name, '/'::text, 1) = (current_app_user_id())::text) AND app_private.current_user_has_hrm_template_permission('hrm.employee.import'::text)));
drop policy if exists knowledge_base_delete_phase4 on storage.objects;
create policy knowledge_base_delete_phase4 on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'knowledge-base'::text) AND app_private.kb_has_action('kb.manage'::text)));
drop policy if exists knowledge_base_insert_phase4 on storage.objects;
create policy knowledge_base_insert_phase4 on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'knowledge-base'::text) AND app_private.kb_has_action('kb.manage'::text)));
drop policy if exists knowledge_base_select_phase4 on storage.objects;
create policy knowledge_base_select_phase4 on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'knowledge-base'::text) AND (app_private.kb_has_action('kb.view'::text) OR app_private.kb_has_action('kb.manage'::text))));
drop policy if exists knowledge_base_update_phase4 on storage.objects;
create policy knowledge_base_update_phase4 on storage.objects as PERMISSIVE for UPDATE to authenticated using (((bucket_id = 'knowledge-base'::text) AND app_private.kb_has_action('kb.manage'::text))) with check (((bucket_id = 'knowledge-base'::text) AND app_private.kb_has_action('kb.manage'::text)));
drop policy if exists p_asset_images_delete on storage.objects;
create policy p_asset_images_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'asset-images'::text) AND ((storage.foldername(name))[1] = 'assets'::text) AND app_private.vehicle_user_can_manage_asset_images(( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists p_asset_images_insert on storage.objects;
create policy p_asset_images_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'asset-images'::text) AND ((storage.foldername(name))[1] = 'assets'::text) AND app_private.vehicle_user_can_manage_asset_images(( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists p_asset_images_select on storage.objects;
create policy p_asset_images_select on storage.objects as PERMISSIVE for SELECT to authenticated using ((bucket_id = 'asset-images'::text));
drop policy if exists p_asset_images_update on storage.objects;
create policy p_asset_images_update on storage.objects as PERMISSIVE for UPDATE to authenticated using (((bucket_id = 'asset-images'::text) AND ((storage.foldername(name))[1] = 'assets'::text) AND app_private.vehicle_user_can_manage_asset_images(( SELECT current_app_user_id() AS current_app_user_id)))) with check (((bucket_id = 'asset-images'::text) AND ((storage.foldername(name))[1] = 'assets'::text) AND app_private.vehicle_user_can_manage_asset_images(( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists p_storage_vehicle_evidence_insert on storage.objects;
create policy p_storage_vehicle_evidence_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'vehicle-trip-evidence'::text) AND app_private.vehicle_user_can_access_evidence(( SELECT current_app_user_id() AS current_app_user_id), name, 'INSERT'::text)));
drop policy if exists p_storage_vehicle_evidence_select on storage.objects;
create policy p_storage_vehicle_evidence_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'vehicle-trip-evidence'::text) AND app_private.vehicle_user_can_access_evidence(( SELECT current_app_user_id() AS current_app_user_id), name, 'SELECT'::text)));
drop policy if exists project_safety_attachments_delete on storage.objects;
create policy project_safety_attachments_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'project-safety-attachments'::text) AND (split_part(name, '/'::text, 1) <> ''::text) AND app_private.safety_can_manage(split_part(name, '/'::text, 1), NULL::text, NULL::text)));
drop policy if exists project_safety_attachments_insert on storage.objects;
create policy project_safety_attachments_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'project-safety-attachments'::text) AND (split_part(name, '/'::text, 1) <> ''::text) AND app_private.safety_can_submit(split_part(name, '/'::text, 1), NULL::text)));
drop policy if exists project_safety_attachments_select on storage.objects;
create policy project_safety_attachments_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'project-safety-attachments'::text) AND (split_part(name, '/'::text, 1) <> ''::text) AND app_private.safety_can_view(split_part(name, '/'::text, 1), NULL::text, NULL::text)));
drop policy if exists public_read on storage.objects;
create policy public_read on storage.objects as PERMISSIVE for SELECT to public using ((bucket_id = 'project-files'::text));
drop policy if exists quality_project_attachments_delete on storage.objects;
create policy quality_project_attachments_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'project-attachments'::text) AND app_private.quality_storage_can_mutate(name)));
drop policy if exists quality_project_attachments_insert on storage.objects;
create policy quality_project_attachments_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'project-attachments'::text) AND app_private.quality_storage_can_mutate(name)));
drop policy if exists quality_project_attachments_update on storage.objects;
create policy quality_project_attachments_update on storage.objects as PERMISSIVE for UPDATE to authenticated using (((bucket_id = 'project-attachments'::text) AND app_private.quality_storage_can_mutate(name))) with check (((bucket_id = 'project-attachments'::text) AND app_private.quality_storage_can_mutate(name)));
drop policy if exists request_template_docx_delete on storage.objects;
create policy request_template_docx_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'workflow-templates'::text) AND app_private.request_template_docx_can_manage(name, ( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists request_template_docx_delete_gate on storage.objects;
create policy request_template_docx_delete_gate on storage.objects as RESTRICTIVE for DELETE to authenticated using (((bucket_id <> 'workflow-templates'::text) OR (name !~~ 'request-template-versions/%'::text) OR app_private.request_template_docx_can_manage(name, ( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists request_template_docx_insert on storage.objects;
create policy request_template_docx_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'workflow-templates'::text) AND app_private.request_template_docx_can_manage(name, ( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists request_template_docx_insert_gate on storage.objects;
create policy request_template_docx_insert_gate on storage.objects as RESTRICTIVE for INSERT to authenticated with check (((bucket_id <> 'workflow-templates'::text) OR (name !~~ 'request-template-versions/%'::text) OR app_private.request_template_docx_can_manage(name, ( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists request_template_docx_select on storage.objects;
create policy request_template_docx_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'workflow-templates'::text) AND app_private.request_template_docx_can_select(name, ( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists request_template_docx_select_gate on storage.objects;
create policy request_template_docx_select_gate on storage.objects as RESTRICTIVE for SELECT to authenticated using (((bucket_id <> 'workflow-templates'::text) OR (name !~~ 'request-template-versions/%'::text) OR app_private.request_template_docx_can_select(name, ( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists request_template_docx_update on storage.objects;
create policy request_template_docx_update on storage.objects as PERMISSIVE for UPDATE to authenticated using (((bucket_id = 'workflow-templates'::text) AND app_private.request_template_docx_can_manage(name, ( SELECT current_app_user_id() AS current_app_user_id)))) with check (((bucket_id = 'workflow-templates'::text) AND app_private.request_template_docx_can_manage(name, ( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists request_template_docx_update_gate on storage.objects;
create policy request_template_docx_update_gate on storage.objects as RESTRICTIVE for UPDATE to authenticated using (((bucket_id <> 'workflow-templates'::text) OR (name !~~ 'request-template-versions/%'::text) OR app_private.request_template_docx_can_manage(name, ( SELECT current_app_user_id() AS current_app_user_id)))) with check (((bucket_id <> 'workflow-templates'::text) OR (name !~~ 'request-template-versions/%'::text) OR app_private.request_template_docx_can_manage(name, ( SELECT current_app_user_id() AS current_app_user_id))));
drop policy if exists safety_passport_storage_delete on storage.objects;
create policy safety_passport_storage_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'safety-passport-attachments'::text) AND app_private.safety_passport_can_manage()));
drop policy if exists safety_passport_storage_insert on storage.objects;
create policy safety_passport_storage_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'safety-passport-attachments'::text) AND app_private.safety_passport_can_manage()));
drop policy if exists safety_passport_storage_select on storage.objects;
create policy safety_passport_storage_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'safety-passport-attachments'::text) AND app_private.safety_passport_can_manage()));
drop policy if exists safety_passport_storage_update on storage.objects;
create policy safety_passport_storage_update on storage.objects as PERMISSIVE for UPDATE to authenticated using (((bucket_id = 'safety-passport-attachments'::text) AND app_private.safety_passport_can_manage())) with check (((bucket_id = 'safety-passport-attachments'::text) AND app_private.safety_passport_can_manage()));
drop policy if exists storage_objects_active_actor_gate on storage.objects;
create policy storage_objects_active_actor_gate on storage.objects as RESTRICTIVE for ALL to authenticated using ((( SELECT current_app_user_id() AS current_app_user_id) IS NOT NULL)) with check ((( SELECT current_app_user_id() AS current_app_user_id) IS NOT NULL));
drop policy if exists wms_transaction_attachments_delete on storage.objects;
create policy wms_transaction_attachments_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'wms-transaction-attachments'::text) AND (split_part(name, '/'::text, 1) <> ''::text) AND app_private.wms_transaction_attachment_can_access(name)));
drop policy if exists wms_transaction_attachments_insert on storage.objects;
create policy wms_transaction_attachments_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'wms-transaction-attachments'::text) AND (split_part(name, '/'::text, 1) <> ''::text) AND app_private.wms_transaction_attachment_can_access(name)));
drop policy if exists wms_transaction_attachments_select on storage.objects;
create policy wms_transaction_attachments_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'wms-transaction-attachments'::text) AND (split_part(name, '/'::text, 1) <> ''::text) AND app_private.wms_transaction_attachment_can_access(name)));
drop policy if exists workflow_attachments_delete on storage.objects;
create policy workflow_attachments_delete on storage.objects as PERMISSIVE for DELETE to authenticated using ((bucket_id = 'workflow-attachments'::text));
drop policy if exists workflow_attachments_insert on storage.objects;
create policy workflow_attachments_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check ((bucket_id = 'workflow-attachments'::text));
drop policy if exists workflow_attachments_select on storage.objects;
create policy workflow_attachments_select on storage.objects as PERMISSIVE for SELECT to authenticated using ((bucket_id = 'workflow-attachments'::text));
drop policy if exists workflow_attachments_update on storage.objects;
create policy workflow_attachments_update on storage.objects as PERMISSIVE for UPDATE to authenticated using ((bucket_id = 'workflow-attachments'::text)) with check ((bucket_id = 'workflow-attachments'::text));
drop policy if exists workflow_comment_attachments_delete on storage.objects;
create policy workflow_comment_attachments_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'workflow-comment-attachments'::text) AND (split_part(name, '/'::text, 1) = 'workflow-subjects'::text) AND (split_part(name, '/'::text, 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text) AND app_private.project_workflow_actor_can_select((split_part(name, '/'::text, 2))::uuid)));
drop policy if exists workflow_comment_attachments_insert on storage.objects;
create policy workflow_comment_attachments_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'workflow-comment-attachments'::text) AND (split_part(name, '/'::text, 1) = 'workflow-subjects'::text) AND (split_part(name, '/'::text, 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text) AND app_private.project_workflow_actor_can_select((split_part(name, '/'::text, 2))::uuid)));
drop policy if exists workflow_comment_attachments_select on storage.objects;
create policy workflow_comment_attachments_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'workflow-comment-attachments'::text) AND (split_part(name, '/'::text, 1) = 'workflow-subjects'::text) AND (split_part(name, '/'::text, 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text) AND app_private.project_workflow_actor_can_select((split_part(name, '/'::text, 2))::uuid)));
drop policy if exists workflow_instance_comment_attachments_delete on storage.objects;
create policy workflow_instance_comment_attachments_delete on storage.objects as PERMISSIVE for DELETE to authenticated using (((bucket_id = 'workflow-instance-comment-attachments'::text) AND (split_part(name, '/'::text, 1) = 'workflow-instances'::text) AND (split_part(name, '/'::text, 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text) AND app_private.workflow_instance_actor_can_select((split_part(name, '/'::text, 2))::uuid)));
drop policy if exists workflow_instance_comment_attachments_insert on storage.objects;
create policy workflow_instance_comment_attachments_insert on storage.objects as PERMISSIVE for INSERT to authenticated with check (((bucket_id = 'workflow-instance-comment-attachments'::text) AND (split_part(name, '/'::text, 1) = 'workflow-instances'::text) AND (split_part(name, '/'::text, 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text) AND app_private.workflow_instance_actor_can_select((split_part(name, '/'::text, 2))::uuid)));
drop policy if exists workflow_instance_comment_attachments_select on storage.objects;
create policy workflow_instance_comment_attachments_select on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'workflow-instance-comment-attachments'::text) AND (split_part(name, '/'::text, 1) = 'workflow-instances'::text) AND (split_part(name, '/'::text, 2) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'::text) AND app_private.workflow_instance_actor_can_select((split_part(name, '/'::text, 2))::uuid)));
drop policy if exists workflow_templates_delete on storage.objects;
create policy workflow_templates_delete on storage.objects as PERMISSIVE for DELETE to anon, authenticated using ((bucket_id = 'workflow-templates'::text));
drop policy if exists workflow_templates_read on storage.objects;
create policy workflow_templates_read on storage.objects as PERMISSIVE for SELECT to anon, authenticated using ((bucket_id = 'workflow-templates'::text));
drop policy if exists workflow_templates_update on storage.objects;
create policy workflow_templates_update on storage.objects as PERMISSIVE for UPDATE to anon, authenticated using ((bucket_id = 'workflow-templates'::text)) with check ((bucket_id = 'workflow-templates'::text));
drop policy if exists workflow_templates_upload on storage.objects;
create policy workflow_templates_upload on storage.objects as PERMISSIVE for INSERT to anon, authenticated with check ((bucket_id = 'workflow-templates'::text));
drop trigger if exists on_auth_user_profile_sync on auth.users;
CREATE TRIGGER on_auth_user_profile_sync AFTER INSERT OR UPDATE OF email, raw_user_meta_data ON auth.users FOR EACH ROW EXECUTE FUNCTION sync_auth_user_profile();
select pg_catalog.set_config('search_path', '', false);
